# .github/workflows/secrets-check.yml
name: Secrets Detection

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at midnight
  workflow_dispatch: # Allow manual triggers for testing

permissions:
  pull-requests: write
  contents: read

jobs:
  secrets:
    name: Secrets Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3
        with:
          scan-depth: 50
